# Generated by Django 5.1.6 on 2025-02-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event', models.CharField(choices=[('industry', 'Industry Visit'), ('academic', 'Academic Visit')], max_length=20)),
                ('visitor_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('college_name', models.CharField(max_length=100)),
                ('UID', models.CharField(max_length=15)),
                ('college_id_card', models.ImageField(upload_to='college_id_cards/')),
            ],
        ),
    ]
