# Generated by Django 5.1.6 on 2025-02-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0002_remove_student_registration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='detail_timestamp',
        ),
    ]
