# Generated by Django 5.1.6 on 2025-02-18 10:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0002_student_registration_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Info.student')),
            ],
        ),
    ]
