# Generated by Django 5.1.6 on 2025-02-27 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0003_remove_studentdetails_detail_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='detail_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
