# Generated by Django 5.1.6 on 2025-02-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0004_student_registration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='detail_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
